kode:
  active: true
  RouteWiringMethodNaming:
    active: true
  MapperFileNaming:
    active: true
  PayloadArgumentName:
    active: true
  UseSurfaceModifier:
    active: true
  UseOnStartEmit:
    active: false
  ComponentFunctionCall:
    active: false
  ImmutableDataClass:
    active: true
    ignoreDescendantsOf: []
  MissingTypeDeclaration:
    active: true
    ignoreInClassesDerivedFrom: []
    ignoreInInterfacesDerivedFrom: []
    ignorePropertiesOfType: []
