kode:
  active: true
  RouteWiringMethodNaming:
    active: true
  MapperFileNaming:
    active: true
  ImmutableDataClass:
    active: true
    ignoreDescendantsOf: []
  MissingTypeDeclaration:
    active: true
    ignoreInClassesDerivedFrom: []
    ignoreInInterfacesDerivedFrom: []
    ignorePropertiesOfType: []
