kode:
  active: true
  MapperFileNaming:
    active: true
  MissingTypeDeclaration:
    active: true
    ignoreInClassesDerivedFrom: []
    ignoreInInterfacesDerivedFrom: []
    ignorePropertiesOfType: []
